Improved efficiency of runtime checks with 'noreturn' attribute
Added 'noreturn' attribute to SisalError(), if supported, to improve
dataflow analysis and resulting code efficiency.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7046,6 +7046,64 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 { echo "$as_me:$LINENO: result: $have_prototypes" >&5
 echo "${ECHO_T}$have_prototypes" >&6; }
 
+have_attr_no_return=no
+{ echo "$as_me:$LINENO: checking for GCC-style noreturn attribute" >&5
+echo $ECHO_N "checking for GCC-style noreturn attribute... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+  extern void fatal() __attribute__ ((noreturn));
+
+int
+main ()
+{
+
+  fatal();
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GCC_ATTR_NORETURN
+_ACEOF
+
+  have_attr_no_return=yes
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $have_attr_no_return" >&5
+echo "${ECHO_T}$have_attr_no_return" >&6; }
+
 have_const=no
 { echo "$as_me:$LINENO: checking for const" >&5
 echo $ECHO_N "checking for const... $ECHO_C" >&6; }
